production:
  secret_key_base: {{ rails_secret_key_base }}
  stripe_publishable_key: {{ stripe_publishable_key }}
  stripe_secret_key: {{ stripe_secret_key }}
  sendgrid_username: {{ sendgrid_username }}
  sendgrid_password: {{ sendgrid_password }}
  plivo_auth_id: {{ plivo_auth_id }}
  plivo_auth_token: {{ plivo_auth_token }}
  plivo_phone_number: {{ plivo_phone_number }}
