// Main Form
export const NEXT_FORM_STEP = 'NEXT_FORM_STEP';

// P1
export const CHANGE_QUERY_STRING = 'CHANGE_QUERY_STRING';

// P2
export const CHANGE_HACKER_NEWS_CHECK = 'CHANGE_HACKER_NEWS_CHECK';
export const CHANGE_REDDIT_CHECK = 'CHANGE_REDDIT_CHECK';

export const CHANGE_SUBREDDIT_STRING = 'CHANGE_SUBREDDIT_STRING';
export const ADD_SUBREDDIT = 'ADD_SUBREDDIT';
export const REMOVE_SUBREDDIT = 'REMOVE_SUBREDDIT';
export const ADD_SUBREDDIT_SUGGESTION = 'ADD_SUBREDDIT_SUGGESTION';
export const REMOVE_SUBREDDIT_SUGGESTION = 'REMOVE_SUBREDDIT_SUGGESTION';

// P3
export const CHANGE_PHONE_NUMBER_STRING = 'CHANGE_PHONE_NUMBER_STRING';
export const CHANGE_EMAIL_STRING = 'CHANGE_EMAIL_STRING';

// Server actions
export const SUBREDDIT_SUGGESTIONS_REQUEST = 'SUBREDDIT_SUGGESTIONS_REQUEST';
export const SUBREDDIT_SUGGESTIONS_SUCCESS = 'SUBREDDIT_SUGGESTIONS_SUCCESS';
export const SUBREDDIT_SUGGESTIONS_FAILURE = 'SUBREDDIT_SUGGESTIONS_FAILURE';

export const CREATE_LISTENER_REQUEST = 'CREATE_LISTENER_REQUEST';
export const CREATE_LISTENER_SUCCESS = 'CREATE_LISTENER_SUCCESS';
export const CREATE_LISTENER_FAILURE = 'CREATE_LISTENER_FAILURE';

// Validation Failed
export const VALIDATION_FAILED = 'VALIDATION_FAILED';
