// Main Form
export const NEXT_FORM_STEP = 'NEXT_FORM_STEP';

// P1
export const CHANGE_QUERY_STRING = 'CHANGE_QUERY_STRING';
export const CHANGE_TEST_TEXT_STRING = 'CHANGE_TEST_TEXT_STRING';

// P2
export const TOGGLE_HACKER_NEWS_CHECK = 'TOGGLE_HACKER_NEWS_CHECK';
export const TOGGLE_REDDIT_CHECK = 'TOGGLE_REDDIT_CHECK';

export const CHANGE_SUBREDDIT_STRING = 'CHANGE_SUBREDDIT_STRING';
export const ADD_SUBREDDIT = 'ADD_SUBREDDIT';
export const REMOVE_SUBREDDIT = 'REMOVE_SUBREDDIT';
export const ADD_SUBREDDIT_SUGGESTION = 'ADD_SUBREDDIT_SUGGESTION';
export const REMOVE_SUBREDDIT_SUGGESTION = 'REMOVE_SUBREDDIT_SUGGESTION';

// P3
export const CHANGE_PHONE_NUMBER_STRING = 'CHANGE_PHONE_NUMBER_STRING';
export const CHANGE_EMAIL_STRING = 'CHANGE_EMAIL_STRING';

// Server actions
export const SUBREDDIT_SUGGESTIONS_REQUEST = 'SUBREDDIT_SUGGESTIONS_REQUEST';
export const SUBREDDIT_SUGGESTIONS_SUCCESS = 'SUBREDDIT_SUGGESTIONS_SUCCESS';
export const SUBREDDIT_SUGGESTIONS_FAILURE = 'SUBREDDIT_SUGGESTIONS_FAILURE';

export const CREATE_LISTENER_REQUEST = 'CREATE_LISTENER_REQUEST';
export const CREATE_LISTENER_SUCCESS = 'CREATE_LISTENER_SUCCESS';
export const CREATE_LISTENER_FAILURE = 'CREATE_LISTENER_FAILURE';

// Validation Failed
export const VALIDATION_FAILED = 'VALIDATION_FAILED';

// Completion Modal
export const OPENED_MODAL = 'OPENED_MODAL';
export const CLOSED_MODAL = 'CLOSED_MODAL';

// Help Modal
export const OPENED_HELP_MODAL = 'OPENED_HELP_MODAL';
export const CLOSED_HELP_MODAL = 'CLOSED_HELP_MODAL';

// Query Content Match Check
export const QUERY_CONTENT_MATCH_CHECK_REQUEST = 'QUERY_CONTENT_MATCH_CHECK_REQUEST';
export const QUERY_CONTENT_MATCH_CHECK_SUCCESS = 'QUERY_CONTENT_MATCH_CHECK_SUCCESS';
export const QUERY_CONTENT_MATCH_CHECK_FAILURE = 'QUERY_CONTENT_MATCH_CHECK_SUCCESS';
